#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Challonger.Resource", IsApplication=true)]

namespace Challonger
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_add_white_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_challonge = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_refresh_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070051
			public const int Text = 2131165265;
			
			// aapt resource value: 0x7f070044
			public const int ViewColorPickerHelper = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int ViewColorPickerHelper1 = 2131165253;
			
			// aapt resource value: 0x7f070069
			public const int ViewTournamentInfoMenuAddParticipant = 2131165289;
			
			// aapt resource value: 0x7f070068
			public const int ViewTournamentInfoMenuEdit = 2131165288;
			
			// aapt resource value: 0x7f070067
			public const int ViewTournamentInfoMenuRefresh = 2131165287;
			
			// aapt resource value: 0x7f070007
			public const int btnAddParticipantInfo_Add = 2131165191;
			
			// aapt resource value: 0x7f07001d
			public const int btnCreateTournament = 2131165213;
			
			// aapt resource value: 0x7f070026
			public const int btnEditParticipantInfo_Delete = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int btnEditParticipantInfo_Save = 2131165221;
			
			// aapt resource value: 0x7f070060
			public const int btnEditTournamentState_Destroy = 2131165280;
			
			// aapt resource value: 0x7f07005c
			public const int btnEditTournamentState_Finalize = 2131165276;
			
			// aapt resource value: 0x7f07005e
			public const int btnEditTournamentState_Reset = 2131165278;
			
			// aapt resource value: 0x7f07005a
			public const int btnEditTournamentState_Start = 2131165274;
			
			// aapt resource value: 0x7f07002e
			public const int btnEditTournamentType = 2131165230;
			
			// aapt resource value: 0x7f07004b
			public const int btnMatchInfoSave = 2131165259;
			
			// aapt resource value: 0x7f070050
			public const int btnNewTournament_View = 2131165264;
			
			// aapt resource value: 0x7f070042
			public const int btnP1ScoreViewMatch = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int btnP2ScoreViewMatch = 2131165251;
			
			// aapt resource value: 0x7f070047
			public const int btnPlayer1ViewMatch = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int btnPlayer2ViewMatch = 2131165256;
			
			// aapt resource value: 0x7f070041
			public const int btnSaveAPIKey = 2131165249;
			
			// aapt resource value: 0x7f07003c
			public const int btnSearch = 2131165244;
			
			// aapt resource value: 0x7f07001c
			public const int chkCreateTournament_Private = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int chkCreateTournament_SE_3rdPlaceMatch = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int chkCreateTournament_Signup = 2131165211;
			
			// aapt resource value: 0x7f070055
			public const int imgParticipantView = 2131165269;
			
			// aapt resource value: 0x7f070000
			public const int linLayAddTournamentState = 2131165184;
			
			// aapt resource value: 0x7f07001e
			public const int linLayEditTournamentState = 2131165214;
			
			// aapt resource value: 0x7f070027
			public const int linLayEditTournamentType = 2131165223;
			
			// aapt resource value: 0x7f070030
			public const int linLayMainTab = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int linMain = 2131165233;
			
			// aapt resource value: 0x7f070063
			public const int linearLayoutTournament = 2131165283;
			
			// aapt resource value: 0x7f070066
			public const int listViewLayViewTournamentInfo = 2131165286;
			
			// aapt resource value: 0x7f070062
			public const int progTournamentListActivityIndicator = 2131165282;
			
			// aapt resource value: 0x7f070056
			public const int progressBar = 2131165270;
			
			// aapt resource value: 0x7f07000e
			public const int radBtnCreateTournamentType_Double = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int radBtnCreateTournamentType_Round = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int radBtnCreateTournamentType_Single = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int radBtnCreateTournamentType_Swiss = 2131165200;
			
			// aapt resource value: 0x7f07002b
			public const int radBtnEditTournamentType_Double = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int radBtnEditTournamentType_Round = 2131165228;
			
			// aapt resource value: 0x7f07002a
			public const int radBtnEditTournamentType_Single = 2131165226;
			
			// aapt resource value: 0x7f07002d
			public const int radBtnEditTournamentType_Swiss = 2131165229;
			
			// aapt resource value: 0x7f07000c
			public const int radGrpCreateTournamentType = 2131165196;
			
			// aapt resource value: 0x7f070029
			public const int radGrpEditTournamentType = 2131165225;
			
			// aapt resource value: 0x7f070034
			public const int radMain = 2131165236;
			
			// aapt resource value: 0x7f070036
			public const int radMainSub = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int radMainURL = 2131165239;
			
			// aapt resource value: 0x7f070035
			public const int radMainView = 2131165237;
			
			// aapt resource value: 0x7f07002f
			public const int relLayMainTab_tab1 = 2131165231;
			
			// aapt resource value: 0x7f070065
			public const int relLayViewTournamentInfo_tab1 = 2131165285;
			
			// aapt resource value: 0x7f070061
			public const int responseView = 2131165281;
			
			// aapt resource value: 0x7f07003d
			public const int space1 = 2131165245;
			
			// aapt resource value: 0x7f070011
			public const int space2 = 2131165201;
			
			// aapt resource value: 0x7f070040
			public const int txtAPIKey = 2131165248;
			
			// aapt resource value: 0x7f070001
			public const int txtAddParticipantInfoName = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int txtAddParticipantInfoName_Edit = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int txtAddParticipantInfoSeed = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int txtAddParticipantInfoSeed_Edit = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int txtAddParticipantInfoUserName = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int txtAddParticipantInfoUserName_Edit = 2131165188;
			
			// aapt resource value: 0x7f07003f
			public const int txtCopyPaste = 2131165247;
			
			// aapt resource value: 0x7f070008
			public const int txtCreateNewTournamentTab = 2131165192;
			
			// aapt resource value: 0x7f070018
			public const int txtCreateTournament_Cap = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int txtCreateTournament_Cap_Edit = 2131165209;
			
			// aapt resource value: 0x7f070016
			public const int txtCreateTournament_Description = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int txtCreateTournament_Description_Edit = 2131165207;
			
			// aapt resource value: 0x7f070009
			public const int txtCreateTournament_Name = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int txtCreateTournament_Name_Edit = 2131165194;
			
			// aapt resource value: 0x7f070014
			public const int txtCreateTournament_Subdomain = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int txtCreateTournament_Subdomain_Edit = 2131165205;
			
			// aapt resource value: 0x7f07000b
			public const int txtCreateTournament_Type = 2131165195;
			
			// aapt resource value: 0x7f070012
			public const int txtCreateTournament_URL = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int txtCreateTournament_URL_Edit = 2131165203;
			
			// aapt resource value: 0x7f07001f
			public const int txtEditParticipantInfoName = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int txtEditParticipantInfoName_Edit = 2131165216;
			
			// aapt resource value: 0x7f070023
			public const int txtEditParticipantInfoSeed = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int txtEditParticipantInfoSeed_Edit = 2131165220;
			
			// aapt resource value: 0x7f070021
			public const int txtEditParticipantInfoUserName = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int txtEditParticipantInfoUserName_Edit = 2131165218;
			
			// aapt resource value: 0x7f07005f
			public const int txtEditTournamentState_Destroy = 2131165279;
			
			// aapt resource value: 0x7f07005b
			public const int txtEditTournamentState_Finalize = 2131165275;
			
			// aapt resource value: 0x7f07005d
			public const int txtEditTournamentState_Reset = 2131165277;
			
			// aapt resource value: 0x7f070059
			public const int txtEditTournamentState_Start = 2131165273;
			
			// aapt resource value: 0x7f070028
			public const int txtEditTournament_Type = 2131165224;
			
			// aapt resource value: 0x7f07003e
			public const int txtGetAPI = 2131165246;
			
			// aapt resource value: 0x7f070039
			public const int txtInfoURL = 2131165241;
			
			// aapt resource value: 0x7f070049
			public const int txtMatchInfoIdent = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int txtMatchInfoStatus = 2131165258;
			
			// aapt resource value: 0x7f07004e
			public const int txtNewTournamentSignup = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int txtNewTournamentSignup_Edit = 2131165263;
			
			// aapt resource value: 0x7f07004c
			public const int txtNewTournamentURL = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int txtNewTournamentURL_Edit = 2131165261;
			
			// aapt resource value: 0x7f070053
			public const int txtParticipantViewDisplayName = 2131165267;
			
			// aapt resource value: 0x7f070052
			public const int txtParticipantViewSeed = 2131165266;
			
			// aapt resource value: 0x7f070054
			public const int txtParticipantViewUsername = 2131165268;
			
			// aapt resource value: 0x7f070046
			public const int txtRoundViewMatch = 2131165254;
			
			// aapt resource value: 0x7f070033
			public const int txtSpinnerText = 2131165235;
			
			// aapt resource value: 0x7f070038
			public const int txtSubdomain = 2131165240;
			
			// aapt resource value: 0x7f07003a
			public const int txtSubdomainURL = 2131165242;
			
			// aapt resource value: 0x7f070058
			public const int txtTournamentInfoBottom = 2131165272;
			
			// aapt resource value: 0x7f070057
			public const int txtTournamentInfoTop = 2131165271;
			
			// aapt resource value: 0x7f07003b
			public const int txtURL = 2131165243;
			
			// aapt resource value: 0x7f070032
			public const int txtWelcome = 2131165234;
			
			// aapt resource value: 0x7f070064
			public const int webTournamentLiveImage = 2131165284;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddParticipantInfoDialogLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateNewTournamentDialogLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditParticipantInfoDialogLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditTournamentTypeLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainTabLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainTabLayout_Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainTabLayout_Settings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MatchInfoListLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NewTournamentDialogLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ParticipantInfoListLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ProgressLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TournamentInfoListLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int TournamentInfoStateDialogLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int TournamentList = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int TournamentLiveImage = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ViewTournamentInfo = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int ViewTournamentInfoMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04008d
			public const int False = 2130968717;
			
			// aapt resource value: 0x7f04008c
			public const int True = 2130968716;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04007c
			public const int btnAddParticipantInfo_Add = 2130968700;
			
			// aapt resource value: 0x7f040013
			public const int btnChangeAPI = 2130968595;
			
			// aapt resource value: 0x7f04007b
			public const int btnEditParticipantInfo_Delete = 2130968699;
			
			// aapt resource value: 0x7f04007a
			public const int btnEditParticipantInfo_Save = 2130968698;
			
			// aapt resource value: 0x7f04006b
			public const int btnEditTournamentState_Destroy = 2130968683;
			
			// aapt resource value: 0x7f040067
			public const int btnEditTournamentState_Finalize = 2130968679;
			
			// aapt resource value: 0x7f040069
			public const int btnEditTournamentState_Reset = 2130968681;
			
			// aapt resource value: 0x7f040065
			public const int btnEditTournamentState_Start = 2130968677;
			
			// aapt resource value: 0x7f04004f
			public const int btnEditType = 2130968655;
			
			// aapt resource value: 0x7f040082
			public const int btnMatchInfoSave = 2130968706;
			
			// aapt resource value: 0x7f040031
			public const int btnNewTournament_View = 2130968625;
			
			// aapt resource value: 0x7f040012
			public const int btnSaveAPIKey = 2130968594;
			
			// aapt resource value: 0x7f04000b
			public const int btnSearch = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int btnSearchCreate = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int cancel = 2130968578;
			
			// aapt resource value: 0x7f04002a
			public const int chkCreateTournament_Private = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int chkCreateTournament_SE_3rdPlaceMatch = 2130968619;
			
			// aapt resource value: 0x7f040029
			public const int chkCreateTournament_Signup = 2130968617;
			
			// aapt resource value: 0x7f040037
			public const int dlg401 = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int dlg404 = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int dlg406 = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int dlg422 = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int dlg500 = 2130968635;
			
			// aapt resource value: 0x7f040032
			public const int dlgAPIEmpty = 2130968626;
			
			// aapt resource value: 0x7f040034
			public const int dlgAPILong = 2130968628;
			
			// aapt resource value: 0x7f040033
			public const int dlgAPIShort = 2130968627;
			
			// aapt resource value: 0x7f040083
			public const int dlgWarningCompleteMatchTitle = 2130968707;
			
			// aapt resource value: 0x7f040084
			public const int dlgWarningCompleteMatchTxt = 2130968708;
			
			// aapt resource value: 0x7f040035
			public const int dlgtxtSubdomain = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int dlgtxtURL = 2130968630;
			
			// aapt resource value: 0x7f04005b
			public const int editTournamentDescription = 2130968667;
			
			// aapt resource value: 0x7f04005c
			public const int editTournamentDescriptionMsg = 2130968668;
			
			// aapt resource value: 0x7f040057
			public const int editTournamentGame = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int editTournamentGameMsg = 2130968664;
			
			// aapt resource value: 0x7f040055
			public const int editTournamentName = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int editTournamentNameMsg = 2130968662;
			
			// aapt resource value: 0x7f04005d
			public const int editTournamentOrganisation = 2130968669;
			
			// aapt resource value: 0x7f04005e
			public const int editTournamentOrganisationMsg = 2130968670;
			
			// aapt resource value: 0x7f040060
			public const int editTournamentState = 2130968672;
			
			// aapt resource value: 0x7f040063
			public const int editTournamentStateReset = 2130968675;
			
			// aapt resource value: 0x7f040062
			public const int editTournamentStateStart = 2130968674;
			
			// aapt resource value: 0x7f040059
			public const int editTournamentTstSuccess = 2130968665;
			
			// aapt resource value: 0x7f040061
			public const int editTournamentType = 2130968673;
			
			// aapt resource value: 0x7f04005a
			public const int editTournamentTypeTstSuccess = 2130968666;
			
			// aapt resource value: 0x7f04003c
			public const int errNoConnection = 2130968636;
			
			// aapt resource value: 0x7f040007
			public const int noAPI = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int ok = 2130968577;
			
			// aapt resource value: 0x7f04001e
			public const int radBtnCreateTournamentType_Double = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int radBtnCreateTournamentType_Round = 2130968607;
			
			// aapt resource value: 0x7f04001d
			public const int radBtnCreateTournamentType_Single = 2130968605;
			
			// aapt resource value: 0x7f040020
			public const int radBtnCreateTournamentType_Swiss = 2130968608;
			
			// aapt resource value: 0x7f04003e
			public const int searchFound = 2130968638;
			
			// aapt resource value: 0x7f04003d
			public const int searchResults = 2130968637;
			
			// aapt resource value: 0x7f040088
			public const int strLoserOf = 2130968712;
			
			// aapt resource value: 0x7f040087
			public const int strMatch = 2130968711;
			
			// aapt resource value: 0x7f040086
			public const int strRound = 2130968710;
			
			// aapt resource value: 0x7f04008b
			public const int strState = 2130968715;
			
			// aapt resource value: 0x7f04008a
			public const int strUsername = 2130968714;
			
			// aapt resource value: 0x7f040089
			public const int strWinnerOf = 2130968713;
			
			// aapt resource value: 0x7f040004
			public const int tabCreate = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int tabMain = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int tabSettings = 2130968581;
			
			// aapt resource value: 0x7f040053
			public const int tstAddParticipantEditDisabled = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int tstAddParticipantNotPending = 2130968660;
			
			// aapt resource value: 0x7f04002c
			public const int tstCreateTournament_Created = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int tstCreateTournament_NameReq = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int tstCreateTournament_URLReq = 2130968622;
			
			// aapt resource value: 0x7f040052
			public const int tstEditDisabled = 2130968658;
			
			// aapt resource value: 0x7f040051
			public const int tstEditEnabled = 2130968657;
			
			// aapt resource value: 0x7f040050
			public const int tstEditType = 2130968656;
			
			// aapt resource value: 0x7f040085
			public const int tstMatchSaved = 2130968709;
			
			// aapt resource value: 0x7f040080
			public const int tstParticipantAdd = 2130968704;
			
			// aapt resource value: 0x7f04007e
			public const int tstParticipantDestroy = 2130968702;
			
			// aapt resource value: 0x7f040081
			public const int tstParticipantNoName = 2130968705;
			
			// aapt resource value: 0x7f04007f
			public const int tstParticipantSave = 2130968703;
			
			// aapt resource value: 0x7f040014
			public const int tstSaveAPI = 2130968596;
			
			// aapt resource value: 0x7f04006f
			public const int tstStateDestroy = 2130968687;
			
			// aapt resource value: 0x7f04006d
			public const int tstStateFinalize = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int tstStateReset = 2130968686;
			
			// aapt resource value: 0x7f04006c
			public const int tstStateStart = 2130968684;
			
			// aapt resource value: 0x7f04005f
			public const int tstTournamentOrganisation = 2130968671;
			
			// aapt resource value: 0x7f04000a
			public const int txtAPIKey = 2130968586;
			
			// aapt resource value: 0x7f040071
			public const int txtAddParticipantInfo = 2130968689;
			
			// aapt resource value: 0x7f04007d
			public const int txtAddParticipantInfoSeed = 2130968701;
			
			// aapt resource value: 0x7f040009
			public const int txtCopyPaste = 2130968585;
			
			// aapt resource value: 0x7f040027
			public const int txtCreateTournament_Cap = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int txtCreateTournament_Cap_Edit = 2130968616;
			
			// aapt resource value: 0x7f040025
			public const int txtCreateTournament_Description = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int txtCreateTournament_Description_Edit = 2130968614;
			
			// aapt resource value: 0x7f04001a
			public const int txtCreateTournament_Name = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int txtCreateTournament_Name_Edit = 2130968603;
			
			// aapt resource value: 0x7f040023
			public const int txtCreateTournament_Subdomain = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int txtCreateTournament_Subdomain_Edit = 2130968612;
			
			// aapt resource value: 0x7f040019
			public const int txtCreateTournament_Title = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int txtCreateTournament_Type = 2130968604;
			
			// aapt resource value: 0x7f040021
			public const int txtCreateTournament_URL = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int txtCreateTournament_URL_Edit = 2130968610;
			
			// aapt resource value: 0x7f040011
			public const int txtDotChallongeSlash = 2130968593;
			
			// aapt resource value: 0x7f040070
			public const int txtEditParticipantInfo = 2130968688;
			
			// aapt resource value: 0x7f040076
			public const int txtEditParticipantInfoEmail = 2130968694;
			
			// aapt resource value: 0x7f040077
			public const int txtEditParticipantInfoEmail_Edit = 2130968695;
			
			// aapt resource value: 0x7f040072
			public const int txtEditParticipantInfoName = 2130968690;
			
			// aapt resource value: 0x7f040073
			public const int txtEditParticipantInfoName_Edit = 2130968691;
			
			// aapt resource value: 0x7f040078
			public const int txtEditParticipantInfoSeed = 2130968696;
			
			// aapt resource value: 0x7f040079
			public const int txtEditParticipantInfoSeed_Edit = 2130968697;
			
			// aapt resource value: 0x7f040074
			public const int txtEditParticipantInfoUserName = 2130968692;
			
			// aapt resource value: 0x7f040075
			public const int txtEditParticipantInfoUserName_Edit = 2130968693;
			
			// aapt resource value: 0x7f04006a
			public const int txtEditTournamentState_Destroy = 2130968682;
			
			// aapt resource value: 0x7f040066
			public const int txtEditTournamentState_Finalize = 2130968678;
			
			// aapt resource value: 0x7f040068
			public const int txtEditTournamentState_Reset = 2130968680;
			
			// aapt resource value: 0x7f040064
			public const int txtEditTournamentState_Start = 2130968676;
			
			// aapt resource value: 0x7f040008
			public const int txtGetAPI = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int txtInfoURL = 2130968590;
			
			// aapt resource value: 0x7f040017
			public const int txtMainSub = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int txtMainURL = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int txtMainView = 2130968598;
			
			// aapt resource value: 0x7f040030
			public const int txtNewTournamentSignup = 2130968624;
			
			// aapt resource value: 0x7f04002f
			public const int txtNewTournamentURL = 2130968623;
			
			// aapt resource value: 0x7f040015
			public const int txtSpinnerText = 2130968597;
			
			// aapt resource value: 0x7f04000d
			public const int txtSubdomain = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int txtSubdomainURL = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int txtURL = 2130968592;
			
			// aapt resource value: 0x7f040006
			public const int txtWelcome = 2130968582;
			
			// aapt resource value: 0x7f04004e
			public const int viewTournamentInfo_3rdPlace = 2130968654;
			
			// aapt resource value: 0x7f040042
			public const int viewTournamentInfo_FinalRank = 2130968642;
			
			// aapt resource value: 0x7f04003f
			public const int viewTournamentInfo_Info = 2130968639;
			
			// aapt resource value: 0x7f040045
			public const int viewTournamentInfo_Info_description = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int viewTournamentInfo_Info_fullURL = 2130968646;
			
			// aapt resource value: 0x7f040049
			public const int viewTournamentInfo_Info_gameName = 2130968649;
			
			// aapt resource value: 0x7f040043
			public const int viewTournamentInfo_Info_name = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int viewTournamentInfo_Info_participantCount = 2130968644;
			
			// aapt resource value: 0x7f040047
			public const int viewTournamentInfo_Info_subdomain = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int viewTournamentInfo_Info_type = 2130968648;
			
			// aapt resource value: 0x7f04004a
			public const int viewTournamentInfo_LiveImage = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int viewTournamentInfo_LiveImageClick = 2130968651;
			
			// aapt resource value: 0x7f040040
			public const int viewTournamentInfo_Matches = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int viewTournamentInfo_Participants = 2130968641;
			
			// aapt resource value: 0x7f04004d
			public const int viewTournamentInfo_Signup = 2130968653;
			
			// aapt resource value: 0x7f04004c
			public const int viewTournamentInfo_State = 2130968652;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
